name: home
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: "^3.6.0"
  flutter: "^3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

dev_dependencies:
  dev_dependency_manager:
    path: ../../core/packages/dev_dependency_manager

flutter:
  uses-material-design: true
